- name: Install and configure Nginx
  hosts: all
  become: yes
  roles:
    - role: update
    - role: install
    - role: template
      vars:
        ansible_host: "{{ hostvars[inventory_hostname].inventory_hostname }}"
        ansible_default_ipv4.address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
    - role: restart